insarlab/PySolid

- README.md
- requirements.txt
- setup.py
+ requirements.txt: add fortran-compiler as a generic way to obtain Fortran compiler cross different platform throug the conda-forge channel
+ setup.py: add scipy to the dependency list
> requirements: add fortran-compiler as a generic way

- README.md
- pysolid/point.py
+ README: update the reference to the IERS 2010 conventions only because:
1. the solid.for program is based on the 2003 conventions, and updated against the latest leap seconds table.
2. there is no change in the used model/literature and the calculation accuracy of solid Earth tides between IERS 2003 and 2010 versions, as shown in Table 0.2 in Petit and Luzum (2010).
+ point: adjust annotation in the PSD plot
> update reference to 2010 convention

- tests/test_SET_grid.py
- tests/test_SET_point.py
This addresses the issue where the test will raise an error in a Windows environment when trying to open the output figure using terminal commands.
> test_SET_grid/point: include terminal commands for Windows

- .circleci/config.yml
Try to fix the following error:
```bash
#!/bin/bash -eo pipefail
export PYTHONUNBUFFERED=1
export PYTHONPATH=${PYTHONPATH}:${HOME}/tools/PySolid
source activate root
mamba install --verbose --yes --file ${HOME}/tools/PySolid/requirements.txt
cd ${HOME}/tools/PySolid/pysolid
f2py -c -m solid solid.for
/bin/bash: line 4: activate: No such file or directory
Exited with code exit status 1
CircleCI received exit code 1
```
> circleci: bugfix2

- pysolid/solid.for
This PR adds the change discussed in #12. 
+ `solid.for`: close the file explicitly for windows OS as reported by @pbrotoisworo.
> solid.for: close the file explicitly for windows OS

- tests/test_SET_grid.py
- tests/test_SET_point.py
Addresses bug when trying to open figures with relative paths as seen in #15.
Output figure path is modified from relative path to absolute path using `os.path.abspath`.
> tests: Modify out figure paths from relative to absolute paths

- .gitignore
- README.md
- setup.py
- src/pysolid/version.py
+ README:
- bring back notes for manual compilation of the Fortran code, as an alternative for the pip install method
- version badge: use shields API to grab the version number, instead of hardwired value
+ setup.py: grab version num from version.py
+ version.py: move the latest release info to the 1st row
+ .gitignore: ignore C extension files, e.g. *.so, as it's not needed in the repo anymore
> bring back notes for manual compilation

- setup.py
> setup: fix the license info inconsistency

- .github/workflows/publish-to-test-pypi.yml
- setup.py
- src/pysolid/__init__.py
- src/pysolid/version.py
+ copy `.github/workflows/publish-to-test-pypi.yml` from mintpy (https://github.com/insarlab/MintPy/pull/827), since pysolid could now be uploaded to PyPI (https://github.com/pypa/pypi-support/issues/2166).
+ version.py:
- copy get_version_info() from mintpy, to grab the individual version number for each commit
- use version number with prefix "v"
+ setup.py:
- grab version from version.py
- grab long_description from README file
> automate PyPI publishing with GitHub Actions

- .github/workflows/publish-to-test-pypi.yml
- setup.py
- src/pysolid/grid.py
- src/pysolid/point.py
- src/pysolid/solid.for
- src/pysolid/version.py
+ version: add Tab for version 0.2.3
+ solid.for: update the file expiration date of the leap second table to 2023-Jun-28 as no leap second will be introduced at the end of Dec 2022, based on Bulletin C 64 (https://hpiers.obspm.fr/eoppc/bul/bulc/bulletinc.64)
+ bugfix for publish-to-pypi:
- grid/point: move solid_grid/point import into sub-functions, to support grabbing pysolid.version without a compiled solid.for
- setup: switch to use pysolid.version to grab the dev version number
- publish-to-pypi: add mamba env + skip wheel build/upload
> wrap up for version 0.2.3

- src/pysolid/grid.py
- src/pysolid/point.py
- src/pysolid/version.py
+ move scipy/matplotlib/skimage into the sub-functions, to avoid adding them to the requirements/host in the conda-forge recipe, as the latter is recommended by conda-forge guideline
+ add release Tag for version 0.2.4
> version 0.2.4: move scipy/matplotlib/skimage into sub-func

- .github/workflows/build-and-publish-to-pypi.yml
An attempt to fix the `upload_pypi` GitHub action error (https://github.com/insarlab/PySolid/actions/runs/3389862941/jobs/5633942424):
```
Error: Unable to resolve action `pypa/gh-action-pypi-publish@release%2Fv1.5.0`, unable to find version `release/v1.5.0`
```
> publish2pypi: fix the GH action version

- .github/workflows/build-and-publish-to-pypi.yml
- README.md
- pyproject.toml
- setup.py
- src/pysolid/solid.for
f2py compiler for py311+ on OS-X scans code explicitly for data types of arguments in functions and subroutines. Implicit declarations are not interpreted, causing wheel builds to fail. The fortran compiler/ f2py setup on linux seems to be fine with this code and wheels build fine already. 
This results in errors such as 
```
In: :solid:src/pysolid/solid.for:detide
vars2fortran: No typespec for argument "mjd".
```
> update solid.for for explicit arg types + attempt to fix pip install by pin setuptools/numpy

- .github/dependabot.yml
- setup.py
+ setup: roll back configs except for version and download_url, after checking the current test pypi page for version 0.2.3.post4 (https://test.pypi.org/project/pysolid/0.2.3.post4/)
+ .github/dependabot: change the interval from daily to weekly
> setup: roll back configs except for version and download_url

- src/pysolid/grid.py
- src/pysolid/point.py
- src/pysolid/solid.for
Seems to fix the race condition which happens when multiple processes are running in the same directory that @vbrancat and I also saw, which I see was already opened in #50 
I started on directly returning arrays from fortran but gave up on it. Maybe some day...
> create unique text file for solid.for to write to, fix #50

- .circleci/config.yml
- README.md
+ circleci: use mambaforge to speedup + use PYSOLID_HOME env
+ README/badge: update colors
> circleci: use mambaforge

- src/pysolid/solid.for
+ update leap sec to Jun 2024 based on IERS Bulletin C 65 (https://datacenter.iers.org/data/latestVersion/16_BULLETIN_C16.txt)
> update leap sec to Jun 2024

- .circleci/config.yml
- docs/requirements.txt
- pyproject.toml
- requirements.txt
- setup.py
- src/pysolid/point.py
- tests/requirements.txt
+ remove matplotlib from the dependency list, as it's not needed in the actual SET calculation, but for result plotting and inspection only, as described in #67.
- remove matplotlib in `pyproject.toml`, `requirements.txt` and `setup.py` files
- `point`: move the module import of matplotlib from top of the script to inside the functions.
+ add `docs/requirements.txt` for extra dependencies needed for running notebooks
+ add `tests/requirements.txt` for extra dependencies needed for running tests
After this PR, we could cut for a maintenance release version 0.3.1 to update the conda-forge recipe.
> dep: drop matplotlib

- README.md
- pyproject.toml
Testing out the dynamic requirements, we'll see if the build works alright with the `"setuptools<60.0"` pin.
> `pyproject.toml`: add dynamic requirements from file

- .github/workflows/build-and-publish-to-pypi.yml
- README.md
+ fix the following error (https://github.com/insarlab/PySolid/actions/runs/7326479653/job/19952659672) by turning on the `merge-multiple` option, as suggested by download-artifact readme
- Checking dist/artifact-source: ERROR InvalidDistribution: Unknown distribution format: 'artifact-source'
+ display the structure of downloaded artifact files, to facilitate the debuging in the future, since this part is easy to have issues
+ update deprecated option names in gh-action-pypi-publish
+ README: fix typo
> pub2pypi: fix unknow dist format error

- .circleci/config.yml
- .github/release.yml
+ .circleci/config.yml: replace mambaforge with miniforge3
+ .github: add release.yml to ignore contributions by bots in release notes
> circleci: replace mambaforge with miniforge3

- .circleci/config.yml
- .gitignore
- CMakeLists.txt
- README.md
- pyproject.toml
- setup.py
- src/pysolid/point.py
- tests/requirements.txt
As setuptools cannot natively call f2py, we call it ourselves by using a custom build extension.
Closes https://github.com/insarlab/PySolid/issues/78
(This seemed like the simplest way to do things - keep using setuptools, and have it manually call f2py under the hood.)
> replace `numpy.distutils` with `CMake` and `scikit-build-core` build backend

- .github/workflows/build-and-publish-to-pypi.yml
- pyproject.toml
+ pyproject.toml: for readme, dependencies, optional-dependencies, use static metadata, instead of dynamic ones, to avoid [the following errors](https://github.com/insarlab/PySolid/actions/runs/9625771487/job/26551314687):
```bash
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
['readme', 'dependencies', 'optional-dependencies'] is not a valid dynamic field. See https://packaging.python.org/specifications/core-metadata for more information.
```
+ `build-and-publish-to-pypi.yml`: update OS versions
- ubuntu: from 20.04 to latest
- macos: from 11 to 13
> `pyproject.toml`: use static metadata for readme/dependencies

- src/pysolid/solid.for
According to [IERS Bulletin C 68](https://datacenter.iers.org/versionMetadata.php?filename=mt/bulletinc-068.txt) no leap second will be introduced at the end of December 2024. The next possible insertion date is therefore end of June 2025.
> update leap second table to 28 Jun 2025 based on IERS Bulletin C 68
